### GET HOME
GET http://{{host}}:{{port}}

### GET CATEGORIES
GET http://{{host}}:{{port}}/api/categories

### POST A CATEGORY
POST http://{{host}}:{{port}}/api/categories
Content-Type: application/json

{
  "type": "Investment",
  "color": "#FCBE44"
}

### GET LABELS
GET http://{{host}}:{{port}}/api/labels

### GET TRANSACTIONS
GET http://{{host}}:{{port}}/api/transactions

### POST A TRANSACTION
POST http://{{host}}:{{port}}/api/transactions
Content-Type: application/json

{
  "name": "Get a food",
  "type": "Expenses",
  "amount": 3000
}

// The below request deletes the above posted transaction
### DELETE A TRANSACTION
DELETE http://{{host}}:{{port}}/api/transactions/{{id}}